version: '2'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8000:8000
    volumes:
      - /var/www/html:/var/www/html
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/ssl:/ect/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt

  mariadb:
    image: mariadb
    expose:
      - 3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
