version: '2'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8000:8000
      - 127.0.0.1:4443:4443
    volumes:
      # Sites directory
      - /var/www/html:/var/www/html:ro
      # Common directory for the ACME challenge (certboot webroot)
      - /var/www/letsencrypt:/var/www/letsencrypt:ro
      # Nginx configs, snippets, dhparams and HTTP Auth passwords
      - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/nginx/snippets:/etc/nginx/snippets:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
      - /etc/nginx/http_auth:/etc/nginx/http_auth:ro
      # Let's Encrypt certificates and etc.
      - /etc/letsencrypt:/etc/letsencrypt:ro
    hostname: nginx
    networks:
      - nginx
    restart: always

  mariadb:
    build:
      context: ./mariadb
    expose:
      - 3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    hostname: mariadb
    networks:
      - mariadb
    restart: always

networks:
  nginx:
    ipam:
      config:
        - subnet: 192.168.0.0/29
  mariadb:
    ipam:
      config:
        - subnet: 192.168.1.0/29
