version: '2'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always

  certbot:
    build:
      context: ./dockerfiles/docker
    depends_on:
      - nginx
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./www:/var/www
    tty: true
    restart: always
