version: '2'

services:
  php-fpm:
    image: php:7.0-fpm
    hostname: example 
    domainname: com
    volumes:
      - /var/www/html/example.com:/var/www/html/example.com
    expose:
      - 9000
    networks:
      - nginx
      - mariadb
    restart: always

networks:
  nginx:
    ipam:
      config:
        - subnet: 192.168.0.8/29
  mariadb:
    ipam:
      config:
        - subnet: 192.168.1.8/29
